resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b

packages:
- '.'

- extra-dep: true
  location:
    git: https://github.com/ghcjs/ghcjs-base.git
    commit: 01014ade3f8f5ae677df192d7c2a208bd795b96c

- extra-dep: true
  location:
      git: https://github.com/ghcjs/ghcjs-dom.git
      commit: d17a8078b05e7b06dc2ad5553016181c20bd2f83
  subdirs:
    - ghcjs-dom
    - ghcjs-dom-jsffi
    - ghcjs-dom-jsaddle

- extra-dep: true
  location:
    git: https://github.com/ghcjs/jsaddle-dom
    commit: 0c3f8c60a15fba49bea8d9e4fa871fb1e40460d4

- extra-dep: true
  location:
    git: https://github.com/reflex-frp/reflex.git
    commit: 9fcbf0792702f48185736cd4bebc2973f299e848

- extra-dep: true
  location:
    git: https://github.com/reflex-frp/reflex-dom.git
    commit: df9fff3a0f4e393db6af0beecabd38156c82aedc
  subdirs:
    - reflex-dom-core
    - reflex-dom

extra-deps:
  - dependent-sum-template-0.0.0.6
  - aeson-1.1.1.0  
  - jsaddle-0.9.2.1
  - prim-uniq-0.1.0.1
  - ref-tf-0.4.0.1
  - zenc-0.1.1

allow-newer: true
